# Generated by Django 6.0.5 on 2026-08-13 13:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('key_version', models.CharField(editable=False, max_length=50)),
                ('rotated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_credential', to='netbox_config_backup.credentialprofile')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
