# Generated by Django 6.0.8 on 2026-08-24 08:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_config_backup', '0013_receiver_protocol_ftp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_replicate', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('base_path', models.CharField(default='netbox-config-backup', max_length=500)),
                ('connect_timeout', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('max_retries', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('retry_delay_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)])),
                ('max_artifact_size', models.PositiveBigIntegerField(default=1073741824, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(10737418240)])),
                ('host_key_type', models.CharField(blank=True, editable=False, max_length=64)),
                ('host_key_public', models.TextField(blank=True, editable=False)),
                ('host_key_fingerprint_sha256', models.CharField(blank=True, editable=False, max_length=100)),
                ('host_key_fingerprint_md5', models.CharField(blank=True, editable=False, max_length=64)),
                ('host_key_approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('last_error_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('credential_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_destinations', to='netbox_config_backup.credentialprofile')),
                ('host_key_approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_config_backup_destinations', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RevisionReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bytes_transferred', models.PositiveBigIntegerField(default=0)),
                ('remote_path', models.CharField(blank=True, max_length=1000)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replicas', to='netbox_config_backup.backupdestination')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='netbox_config_backup.configrevision')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['destination', 'status', 'next_retry_at'], name='ncb_replica_retry')],
                'constraints': [models.UniqueConstraint(fields=('revision', 'destination'), name='ncb_replica_revision_destination')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
