# Generated by Django 6.0.8 on 2026-08-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0014_backupdestination_revisionreplica'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdestination',
            name='allow_insecure_ftp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupdestination',
            name='protocol',
            field=models.CharField(default='sftp', max_length=8),
        ),
    ]
