# Generated by Django 6.0.8 on 2026-08-24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_config_backup", "0015_backupdestination_allow_insecure_ftp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupdestination",
            name="integrity_audit_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Automatically verify successful FTP revision copies without "
                    "changing them."
                ),
            ),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="integrity_audit_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="daily",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="integrity_audit_time",
            field=models.TimeField(default=datetime.time(4, 0)),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="integrity_audit_weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="last_integrity_audit_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="last_integrity_audit_problem_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="last_integrity_audit_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthy", "Healthy"),
                    ("problems", "Problems found"),
                    ("failed", "Failed"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="backupdestination",
            name="next_integrity_audit_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
            ),
        ),
    ]
