from __future__ import annotations

from dataclasses import dataclass
from datetime import time

from dcim.models import Platform
from django.db import transaction

from netbox_config_backup.models import (
    BackupPolicy,
    ConnectionProfile,
    CredentialProfile,
    PlatformMapping,
    RetentionPolicy,
)

EXAMPLE_PREFIX = "[Example]"
EXAMPLE_PLATFORM_SLUG = "config-backup-example-fake"


@dataclass(frozen=True, slots=True)
class ExampleConfiguration:
    retention_policy: RetentionPolicy
    backup_policy: BackupPolicy
    connection_profile: ConnectionProfile
    credential_profile: CredentialProfile
    platform: Platform
    platform_mapping: PlatformMapping


def get_example_configuration() -> ExampleConfiguration | None:
    retention = RetentionPolicy.objects.filter(name=f"{EXAMPLE_PREFIX} Standard retention").first()
    policy = BackupPolicy.objects.filter(name=f"{EXAMPLE_PREFIX} Daily at 03:00").first()
    connection = ConnectionProfile.objects.filter(
        name=f"{EXAMPLE_PREFIX} Secure SSH defaults"
    ).first()
    credential = CredentialProfile.objects.filter(
        name=f"{EXAMPLE_PREFIX} External secret reference"
    ).first()
    platform = Platform.objects.filter(slug=EXAMPLE_PLATFORM_SLUG).first()
    mapping = PlatformMapping.objects.filter(platform=platform).first() if platform else None
    if not all((retention, policy, connection, credential, platform, mapping)):
        return None
    return ExampleConfiguration(
        retention_policy=retention,
        backup_policy=policy,
        connection_profile=connection,
        credential_profile=credential,
        platform=platform,
        platform_mapping=mapping,
    )


@transaction.atomic
def create_or_reset_example_configuration() -> ExampleConfiguration:
    retention, _ = RetentionPolicy.objects.update_or_create(
        name=f"{EXAMPLE_PREFIX} Standard retention",
        defaults={
            "keep_all_days": 7,
            "daily_days": 30,
            "weekly_weeks": 12,
            "monthly_months": 12,
            "minimum_changed_revisions": 10,
            "unchanged_run_days": 90,
            "changed_run_days": 180,
            "failed_run_days": 180,
        },
    )
    policy, _ = BackupPolicy.objects.update_or_create(
        name=f"{EXAMPLE_PREFIX} Daily at 03:00",
        defaults={
            "enabled": True,
            "schedule_type": "daily",
            "interval_minutes": None,
            "time_of_day": time(3, 0),
            "timezone_mode": "site",
            "jitter_minutes": 15,
            "connection_timeout": 15,
            "command_timeout": 60,
            "max_retries": 3,
            "retry_backoff_minutes": [5, 15, 60],
            "store_mode": "changed_only",
            "retention_policy": retention,
        },
    )
    connection, _ = ConnectionProfile.objects.update_or_create(
        name=f"{EXAMPLE_PREFIX} Secure SSH defaults",
        defaults={
            "address_preference": "primary4_first",
            "port": 22,
            "connect_timeout": 15,
            "command_timeout": 60,
            "keepalive": 30,
            "verify_host_key": True,
            "known_hosts_path": "/etc/ssh/ssh_known_hosts",
        },
    )
    credential, _ = CredentialProfile.objects.update_or_create(
        name=f"{EXAMPLE_PREFIX} External secret reference",
        defaults={
            "provider_id": "environment",
            "secret_reference": "env://CONFIG_BACKUP_EXAMPLE",
            "auth_type": "password",
        },
    )
    platform, _ = Platform.objects.update_or_create(
        slug=EXAMPLE_PLATFORM_SLUG,
        defaults={"name": f"{EXAMPLE_PREFIX} Fake network OS"},
    )
    mapping, _ = PlatformMapping.objects.update_or_create(
        platform=platform,
        defaults={
            "driver_id": "fake",
            "connection_profile": connection,
            # Intentionally not connected: the placeholder provider is not executable.
            "credential_profile": None,
            "enabled": True,
            "driver_options": {
                "config": (
                    "hostname example-router\n"
                    "interface Loopback0\n"
                    " description generated by FakeDriver\n"
                )
            },
        },
    )
    return ExampleConfiguration(
        retention_policy=retention,
        backup_policy=policy,
        connection_profile=connection,
        credential_profile=credential,
        platform=platform,
        platform_mapping=mapping,
    )
